/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "Stm32F446xx.h"
#include "ErrType.h"

#include "RCC_Private.h"
#include "RCC_Interface.h"

#include "GPIO_prv.h"
#include "GPIO_interface.h"


#include "SYSTICK_interface.h"

int main(void)
{
	/*GPIO PIN CONFIGURATIONS*/
	PinConfig_t Local_PinConfig={
			.Port=PORTA,
			.PinNum=PIN5,
			.Mode=OUTPUT,
			.Speed=LOW_SPEED,
			.OutputType=PUSH_PULL,
			.PullType=PULLUP,
			.AltFunc=AF0
	};

	RCC_SetClkSts(HSE, ON);
	RCC_SetSysClk(HSE);
	RCC_AHB1EnableClock(GPIOAEN);
	GPIO_u8PinInit(&Local_PinConfig);
	GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH);

	/* Loop forever */
	while(1)
	{
		GPIO_u8TogglePinValue(PORTA, PIN5);
		SYSTICK_DelayMs(1000);
	}
}
